### ISSUE TITLE
Compatibility version in osx is screwed up

### ISSUE THREAD

**Issue by isuruf** [conda-forge/gtk3-feedstock#14]
In OSX,
`gtk3-3.24.18-h41d95d7_1.tar.bz2` has compatibility version `2411.0.0`
`gtk3-3.24.21-h41d95d7_0.tar.bz2` has compatibility version `2405.0.0`

Compatibility version should go up, not down

**Comment by tschoonj** [comment]
they have made a bit of a mess of their meson versioning over the last couple of months, but supposedly it is fixed now. Unfortunately, this may mean that you will need to recompile any software that is linked to it.

Are their any affected conda packages?

**Comment by isuruf** [comment]
Thanks for the info. gtkmm is affected
