### ISSUE TITLE
Future GSettings problems

### ISSUE THREAD

**Issue by tschoonj** [conda-forge/gtk3-feedstock#5]
Hi,

First of all: many thanks for adding this complicated recipe to conda-forge! 

I am looking into using it, and I think I have discovered a potential issue that will affect this recipe in the future. 

This recipe installs `$PREFIX/share/glib-2.0/schemas/gschemas.compiled`, which contains a binary representation of all GSettings schemas provided by all libraries and apps that support it. Typically this file is not owned by a particular package, and package managers will update this file in a post installation step by running `glib-compile-schemas $PREFIX/share/glib-2.0/schemas`.

If you agree, I will open a PR that will fix this. This will require also require `DESTDIR` to be set to '/', to avoid invoking the meson post install script, where this otherwise gets done.

**Comment by ryanvolz** [comment]
Yes, I think setting the DESTDIR and therefore not doing those post-install actions would be a good improvement, so please proceed with a PR.

For future reference, here's where that post-install stuff happens in the meson build infrastructure:
https://github.com/GNOME/gtk/blob/mainline/build-aux/meson/post-install.py

In addition to the GSettings schemas, it also updates the icon cache and module cache.

A future strategy we could take is to use a conda post-link script to do these post-install things. The `gdk-pixbuf` package already does something like this for its loader cache that we can emulate:
https://github.com/conda-forge/gdk-pixbuf-feedstock/blob/master/recipe/post-link.sh
That then requires packages that would update the cache to call the `gdk-pixbuf` post-link script from the post-link and pre-unlink recipe scripts:
https://github.com/conda-forge/librsvg-feedstock/tree/master/recipe
