### ISSUE TITLE
Enable Wayland support

### ISSUE THREAD

**Issue by hongy19** [conda-forge/gtk3-feedstock#61]
i installed gtk3 with conda install gtk3, but it seems gdk/gdkwayland.h are not included

`(gtk) hongy19@WSL cairo$ ls /home/hongy19/miniconda3/envs/gtk/include/gtk-3.0/gdk/gdkwayland.h
ls: cannot access '/home/hongy19/miniconda3/envs/gtk/include/gtk-3.0/gdk/gdkwayland.h': No such file or directory

(gtk) hongy19@WSL cairo$ ls /home/hongy19/miniconda3/envs/gtk/include/gtk-3.0/gdk/
deprecated             gdkcairo.h   gdkdevice.h         gdkdevicetool.h      gdkdnd.h             gdkevents.h        gdkglcontext.h  gdkkeysyms-compat.h  gdkmonitor.h  gdkprivate.h    gdkrgba.h    gdkselection.h  gdktypes.h          gdkwindow.h
gdkapplaunchcontext.h  gdkconfig.h  gdkdevicemanager.h  gdkdisplay.h         gdkdrawingcontext.h  gdkframeclock.h    gdk.h           gdkkeysyms.h         gdkpango.h    gdkproperty.h   gdkscreen.h  gdktestutils.h  gdkversionmacros.h  gdkx.h
gdk-autocleanup.h      gdkcursor.h  gdkdevicepad.h      gdkdisplaymanager.h  gdkenumtypes.h       gdkframetimings.h  gdkkeys.h       gdkmain.h            gdkpixbuf.h   gdkrectangle.h  gdkseat.h    gdkthreads.h    gdkvisual.h         x11`

**Comment by tschoonj** [comment]
That does not surprise me, given that we explicitly disable wayland support:

https://github.com/conda-forge/gtk3-feedstock/blob/main/recipe/build.sh#L24

**Comment by hongy19** [comment]
> That does not surprise me, given that we explicitly disable wayland support:
> 
> https://github.com/conda-forge/gtk3-feedstock/blob/main/recipe/build.sh#L24

@tschoonj  thanks! that is aligned with what I see.
by the way, is there any any reason to disable wayland support on gtk3?

**Comment by ryanvolz** [comment]
> by the way, is there any any reason to disable wayland support on gtk3?

Wayland was not available as a conda-forge package for a long time, so we couldn't enable it without someone finding the motivation to add the appropriate packages to conda-forge. But now I see that [`wayland`](https://github.com/conda-forge/wayland-feedstock) was added a couple months ago, and I think this is the first time any of us have noticed that fact. So it should be possible to enable it now.

**Comment by hongy19** [comment]
> > by the way, is there any any reason to disable wayland support on gtk3?
> 
> Wayland was not available as a conda-forge package for a long time, so we couldn't enable it without someone finding the motivation to add the appropriate packages to conda-forge. But now I see that [`wayland`](https://github.com/conda-forge/wayland-feedstock) was added a couple months ago, and I think this is the first time any of us have noticed that fact. So it should be possible to enable it now.

enable wayland will be great. I has tried pywayland and it could work.

```
(gtk) hongy19@WSL ~$ conda list |grep wayland
pywayland                 0.4.15                   pypi_0    pypi
wayland                   1.22.0               hec8639a_0    defaults
```
