### ISSUE TITLE
Errors with post-link script if a space is in the conda path

### ISSUE THREAD

**Issue by ryanvolz** [conda-forge/gtk3-feedstock#8]
Issue:
If a user has a space in their conda path, the post-link script will fail with ".... is not recognized as an internal or external command" because it tries to run the partial path before the space as a program.

The fix should be to quote the command path in the post-link script.
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by stuarteberg** [comment]
I thought miniconda/anaconda generally refused to install into paths that contain spaces.  Am I misremembering?

**Comment by ryanvolz** [comment]
I did think that was true, but I got a report from a user on Windows 10:
```
Executing transaction: \ b"'C:\\Users\\Frank' is not recognized as an internal or external command,\noperable program or batch file.\n"
done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'conda-forge::gdk-pixbuf-2.38.2-h67ea0bb_3'.
Rolling back transaction: doneLinkError: post-link script failed for package conda-forge::gdk-pixbuf-2.38.2-h67ea0bb_3
location of failed script: C:\Users\Frank Lind\.conda\envs\openradar2020\Scripts\.gdk-pixbuf-post-link.bat
==> script messages <==
'C:\Users\Frank' is not recognized as an internal or external command,
operable program or batch file.
```

So it looks like it allowed him to create the environment in a user directory with a space in the name, and that caused an issue (with the gdk-pixbuf post-link script, but the problem is the same here). I'm not sure if the pull request I did fixes this, but I think it should.

**Comment by stuarteberg** [comment]
Makes sense.  Looks like other `post-link.bat` scripts attempt to support spaces in the same manner.  Here's a long thread of complaints and discussion:

https://github.com/ContinuumIO/anaconda-issues/issues/716
